name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./internal/...

  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Get tinygo runtime
        run: |

          wget -P /tmp/ https://github.com/tinygo-org/tinygo/releases/download/v0.20.0/tinygo_0.20.0_amd64.deb
          sudo dpkg -i /tmp/tinygo_0.20.0_amd64.deb

      - name: Build WASM
        run: |
          tinygo build -o astro.wasm -target wasm ./cmd/astro-wasm/astro-wasm.go
          cp ./lib/compiler/astro.wasm ./lib/compiler/deno/astro.wasm

      - name: Install deps
        env:
          CI: true
        run: yarn --frozen-lockfile --ignore-engines
          yarn build:compiler

      - name: Build JS
        run: yarn build:compiler

      - name: Test WASM
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn lint
