name: Test

on:
  push:
    branches: ['main', 'next']
  pull_request:
    branches: ['main', 'next']

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./internal/...

  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Build WASM
        run: make wasm

      - name: Install NPM Dependencies
        run: pnpm install
        env:
          CI: true

      - name: Build JS
        run: pnpm run build:compiler

      - name: Test WASM
        run: pnpm test:ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn lint
