name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Get tinygo runtime
        run: |
          wget -P /tmp/ https://github.com/tinygo-org/tinygo/releases/download/v0.20.0/tinygo_0.20.0_amd64.deb
          sudo dpkg -i /tmp/tinygo_0.20.0_amd64.deb

      - name: Build WASM
        run: |
          tinygo build -no-debug -o ./lib/compiler/astro.wasm -target wasm ./cmd/astro-wasm/astro-wasm.go
          cp ./lib/compiler/astro.wasm ./lib/compiler/deno/astro.wasm

      - name: Install NPM Dependencies
        run: yarn install --prefer-offline --frozen-lockfile --ignore-engines
        env:
          CI: true

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: '[ci] release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
